#setup.template.settings:
#setup.kibana:

metricbeat.modules:
  - module: system
    enabled: false

  - module: logstash
    enabled: true
    metricsets:
      - node
      - node_stats
    period: 10s
    hosts: ["logstash:9600"]
    xpack.enabled: true

  - module: elasticsearch
    enabled: true
    metricsets:
      - ccr
      - enrich
      - cluster_stats
      - index
      - index_recovery
      - index_summary
      - ml_job
      - node_stats
      - shard
    period: 10s
    hosts: ["http://elasticsearch-production:9200"]
    xpack.enabled: true

output.elasticsearch:
  enabled: true
  hosts: ["elasticsearch-monitoring:9200"]
  username: elastic
  password: nomnom
